//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostenovaMiracleShow
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommodityPosition
    {
        public CommodityPosition()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int CommodityPositionID { get; set; }
        public int ProductID { get; set; }
        public double Size { get; set; }
        public int QuantityInStock { get; set; }
        public int SizeID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sizes Sizes { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
