//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostenovaMiracleShow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GostenovaMiracleShowEntities : DbContext
    {
        private static GostenovaMiracleShowEntities _context;
        public static GostenovaMiracleShowEntities GetContext()
        {
            if (_context == null)
                _context = new GostenovaMiracleShowEntities();
            return _context;
        }
        public GostenovaMiracleShowEntities()
            : base("name=GostenovaMiracleShowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Category { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<CommodityPosition> CommodityPosition { get; set; }
        public DbSet<Manufacture> Manufacture { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderItem> OrderItem { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Sizes> Sizes { get; set; }
        public DbSet<SubCategory> SubCategory { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
    }
}
