//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostenovaMiracleShow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int OrderID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
