//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostenovaMiracleShow
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Product
    {
        public Product()
        {
            this.CommodityPosition = new HashSet<CommodityPosition>();
        }
    
        public int ProductID { get; set; }
        public string Images { get; set; }
        public string ProductPhotoPath
        {
            get
            {
                if (Images == null)
                    return null;
                return "Images/" + Images;
            }
        }
        public string ProductName { get; set; }
        public string Discription { get; set; }
        public string Compound { get; set; }
        public decimal Price { get; set; }
        public int ManufactureID { get; set; }
        /*public string ManufactureTitle {  
            get
            { 
                return this.Manufacture.Title;
            }
        }*/
        //public string ManufactureTitle => this.Manufacture?.Title ?? "Нет производителя";

        public string ManufactureTitle => this.Manufacture?.Manufacture1;
        public string CategoryTitle => this.Category?.CategoryName;
        public string SubCategoryTitle => this.SubCategory?.SubCategoryName;

        public int CategoryID { get; set; }
        public int SubCategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<CommodityPosition> CommodityPosition { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
