//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GostenovaMiracleShow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sizes
    {
        public Sizes()
        {
            this.CommodityPosition = new HashSet<CommodityPosition>();
        }
    
        public int SizeID { get; set; }
        public decimal SizeValue { get; set; }
        public string SizeLabel { get; set; }
    
        public virtual ICollection<CommodityPosition> CommodityPosition { get; set; }
    }
}
